// <auto-generated />
using CodeFirstApproch.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstApproch.Migrations
{
    [DbContext(typeof(StudentDBContext))]
    [Migration("20250303111120_codefirstapprochDB")]
    partial class codefirstapprochDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstApproch.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("StudenAge");

                    b.Property<int>("ContactNo")
                        .HasColumnType("int")
                        .HasColumnName("GurdianContactNo");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FatherName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("StudenGender");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("StudenClass");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StudenName");

                    b.HasKey("ID");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
